- id: npm-task-if-exists
  name: Run an NPM task if it exists
  entry: ./scripts/node/npm-task-if-exists.sh
  language: script
  types_or:
    - javascript
    - ts
  pass_filenames: false
- id: local-repo-hook
  name: Run the repo-local hook script
  description: This may double-run any previously installed pre-commit hooks.
  entry: ./scripts/local-scripts.sh
  language: script
  always_run: true
  pass_filenames: false
